overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel_webio.yaml
targets:
  - setup.py: custom_setup.py.jj2
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - .travis.yml: travis.yml.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - README.rst: custom_readme.rst.jj2
